import React, { useMemo } from 'react';
import {
  ReactFlow,
  Background,
  Controls,
  BackgroundVariant,
} from '@xyflow/react';
import '@xyflow/react/dist/style.css';

import type { GeneratedWorkflow } from '../../types/workflow';
import { workflowToGraph } from './workflowToGraph';
import { TriggerNode } from './nodes/TriggerNode';
import { ConditionNode } from './nodes/ConditionNode';
import { ActionNode } from './nodes/ActionNode';
import { RecipientNode } from './nodes/RecipientNode';
import { GitBranch, AlertCircle } from 'lucide-react';

interface WorkflowGraphProps {
  workflow: GeneratedWorkflow | null;
}

const nodeTypes = {
  triggerNode: TriggerNode,
  conditionNode: ConditionNode,
  actionNode: ActionNode,
  recipientNode: RecipientNode,
};

export const WorkflowGraph: React.FC<WorkflowGraphProps> = ({ workflow }) => {
  const { nodes, edges } = useMemo(() => {
    return workflowToGraph(workflow);
  }, [workflow]);

  if (!workflow || nodes.length === 0) {
    return (
      <div className="w-full h-full min-h-[400px] flex flex-col items-center justify-center bg-slate-50 text-slate-500 p-8 text-center border border-dashed border-slate-200 rounded-xl">
        <div className="w-12 h-12 rounded-full bg-slate-100 flex items-center justify-center text-slate-400 mb-3">
          <GitBranch className="w-6 h-6" />
        </div>
        <h4 className="text-sm font-semibold text-slate-700 mb-1">
          No Visual Graph Available
        </h4>
        <p className="text-xs text-slate-500 max-w-sm">
          Complete the workflow to see its visual representation. The graph renders automatically once the assistant generates the final workflow specification.
        </p>
        <div className="mt-4 flex items-center gap-1.5 text-[11px] text-amber-700 bg-amber-50 px-3 py-1.5 rounded-lg border border-amber-200">
          <AlertCircle className="w-3.5 h-3.5" />
          <span>Status must be GENERATED by the backend.</span>
        </div>
      </div>
    );
  }

  return (
    <div className="w-full h-full min-h-[460px] relative bg-slate-50/50 rounded-xl overflow-hidden border border-slate-200">
      <ReactFlow
        nodes={nodes}
        edges={edges}
        nodeTypes={nodeTypes}
        fitView
        fitViewOptions={{ padding: 0.2 }}
        nodesDraggable={false}
        nodesConnectable={false}
        elementsSelectable={false}
        nodesFocusable={false}
        edgesFocusable={false}
        autoPanOnNodeDrag={false}
        panOnDrag={true}
        zoomOnScroll={true}
        preventScrolling={false}
      >
        <Background variant={BackgroundVariant.Dots} gap={16} size={1} color="#cbd5e1" />
        <Controls
          showInteractive={false}
          className="bg-white border border-slate-200 shadow-xs rounded-lg overflow-hidden"
        />
      </ReactFlow>
    </div>
  );
};
